"""empty message

Revision ID: 734f84339db2
Revises: 67f252a421d7
Create Date: 2018-06-29 19:33:31.224029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734f84339db2'
down_revision = '67f252a421d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('hid', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('seats', sa.String(length=256), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['cinemas.cid'], ),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_index(op.f('ix_hall_name'), 'hall', ['name'], unique=True)
    op.create_table('hall_schedule',
    sa.Column('hsid', sa.Integer(), nullable=False),
    sa.Column('or_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dis_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('hid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['cinemas.cid'], ),
    sa.ForeignKeyConstraint(['hid'], ['hall.hid'], ),
    sa.ForeignKeyConstraint(['mid'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('hsid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall_schedule')
    op.drop_index(op.f('ix_hall_name'), table_name='hall')
    op.drop_table('hall')
    # ### end Alembic commands ###
