"""empty message

Revision ID: 83377b66d3cd
Revises: 734f84339db2
Create Date: 2018-06-30 08:26:09.122452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83377b66d3cd'
down_revision = '734f84339db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=10), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('banner_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
